### ISSUE TITLE
 workflow configuration in sub-folders fails

### ISSUE THREAD

**Issue by romelgomez** [romelgomez/docker-monster#1]
To-Do

- [ ]  implement nx as monorepo.

ref: 

-  https://github.com/orgs/community/discussions/18055#discussioncomment-3703595
- https://github.com/romelgomez/docker-monster/actions/runs/10224373575/job/28292024032

**Comment by romelgomez** [comment]
this resolve this issue:

https://stackoverflow.com/questions/68527897/how-to-specifiy-path-for-actions-setup-node-in-github


```

The support for custom path (relative to repository root) was added in version 2.4: https://github.com/actions/setup-node/releases/tag/v2.4.0

You can try specifying '**/package-lock.json' in the cache-dependency-path (it didn't work for me with other patterns).
Also you can try setting the working directory (either for all jobs or your nodejstest specific job) to point to your frontend folder.
  nodejstest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'frontend' # Here the path to the folder where package-lock.json is located.
    strategy:
      matrix:
        node-version: [16.x] # Are you are missing this specification?
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json' # THIS PATTERN did the trick for me.
```
